name: Build and Release
on: 
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build for ${{ matrix.goos }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: ["amd64", "amd32", "arm64", "arm32","x86","x64"]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o killer-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: killer-${{ matrix.goos }}-${{ matrix.goarch }}
        path: killer-${{ matrix.goos }}-${{ matrix.goarch }}
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Release  
      uses: softprops/action-gh-release@v1
      with:
        files: |
          killer-*
